services:
  postgres:
    image: postgres:15-alpine
    container_name: cafeteria_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cafeteria_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Mapping files numerically to ensure order of execution
      - ./db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
      - ./db/reports_vw.sql:/docker-entrypoint-initdb.d/03-reports_vw.sql
      - ./db/indexes.sql:/docker-entrypoint-initdb.d/04-indexes.sql
      - ./db/roles.sql:/docker-entrypoint-initdb.d/05-roles.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d cafeteria_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./app-cafeteria
      dockerfile: Dockerfile
    container_name: cafeteria_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      # Connection string for the app_user (restricted access)
      DATABASE_URL: postgres://app_user:cafeteria_secure_pass@postgres:5432/cafeteria_db
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
